import {card} from "./cards";
import {PRINTED_PACK} from "./printed-pack";
import {CUSTOM_PACK} from "./custom-pack";
/** Independently written interface explanations of LE pp. 6–11 and 16–24.
 * Describe the actual action and its limits; do not substitute abbreviated hints
 * or reproduce the publisher's printed card text. */
export const RULE_PROMPTS: Readonly<Record<string,readonly [string,string]>> = {
  BLUE_DESTINATION:["选择一种付款方式：让每位对手把金币交给你，或让每位对手把金币付入奖池。两种方式的金额见能力说明。","Choose whether every opponent pays gold to you or to the stakes. The power description gives the amount for each option."],
  GIVE_DRAGON_OR_GOLD:["从自己的手牌中选一张符合条件的龙牌，公开后交给发动此能力的玩家；也可以选择向该玩家支付 5 金币。","Choose an eligible dragon from your own hand to reveal and give to the player using this power, or choose to pay that player 5 gold."],
  LOWEST_ANTE_CARD:["从当前可选的下注牌中选一张点数最低的牌。并列时由你选择；需要取第二张时，会再从剩余最低点数的牌中选择。","Select a lowest-strength ante card from the current options. You decide between tied cards. If a second card is needed, you will then choose from the lowest-strength cards remaining."],
  KEEP_ONE_ANTE_CARD:["你的手牌已有 9 张。从刚选出的两张下注牌中选一张加入手牌；另一张留在公开下注区。","You already have 9 hand cards. Choose one of the two selected ante cards to add to your hand; leave the other in the public ante area."],
  REPLACE_OTHER_FLIGHT_CARD:["从自己的牌阵中选一张其他牌，将它弃掉，再用牌堆顶的 1 张牌放到原位置。不能选择正在发动此能力的牌。","Choose another card in your own flight to discard. The top card of the deck will replace it in the same position. You cannot choose the card using this power."],
  REPLACE_WYRMLING:["你可以从自己的手牌中选一张符合阵营条件的龙牌，替换正在发动能力的牌并发动新牌能力；也可以保留原牌，不作替换。","Choose an eligible dragon from your hand to replace the card using this power and trigger the new card's power, or keep the original card without replacing it."],
  TRIGGER_REPLACEMENT:["替换已经完成。现在选择是否发动新牌的能力；即使不发动，新牌也会正面朝上留在你的牌阵中。","The replacement is complete. Choose whether to trigger the new card's power. If you decline, the new card still stays face up in your flight."],
  WEAKEST_OPPONENT:["选择一位当前牌阵总强度最低的对手，让该对手向你支付金币。只比较对手，不把你自己算在内；最低值并列时由你选一位。","Choose an opponent with the lowest current flight total to pay you gold. Compare opponents only, excluding yourself. You choose one player if several share the lowest total."],
  STRONGEST_OPPONENT:["选择一位当前牌阵总强度最高的对手，让该对手向你支付金币，再从其手牌中随机拿走 1 张。只比较对手；最高值并列时由你选一位。","Choose an opponent with the highest current flight total to pay you gold, then take 1 random card from that opponent's hand. Compare opponents only; you choose one player if the highest total is tied."],
  REMOVE_WEAKER_DRAGON:["从任意玩家的牌阵中选一张符合点数条件的龙牌，将它放入弃牌堆。自己的龙牌也可以被选中；只要有符合条件的牌，就必须选一张。","Choose an eligible lower-strength dragon from any player's flight and put it in the discard pile. This can be your own dragon. You must choose one if an eligible dragon exists."],
  EXCHANGE_HAND_CARDS:["先选好要弃掉的手牌并确认，再从牌堆里抽相同数量的牌加入手牌。你可以选任意张，也可以一张都不选。","Choose all the hand cards you want to discard and confirm. Then draw the same number of cards from the deck into your hand. You may choose any number, including none."],
  SWAP_MORTAL:["你可以选择对手牌阵中的一张凡人牌，与自己正在发动能力的凡人牌交换，再发动换来的牌的能力；也可以保持原样，不交换。","Choose a mortal in an opponent's flight to exchange with your mortal using this power, then trigger the mortal you receive. You may instead keep your card and make no exchange."],
  NEXT_GOOD_DRAGON_POWER:["从列出的己方善龙中选一张，接下来发动它的能力。由你决定先后顺序；轮到某张牌时若它仍在自己的牌阵中，就发动一次。","Choose which of the listed good dragons in your flight triggers next. You choose the order; each card triggers once if it is still in your flight when its turn comes."],
  COPY_HAND_DRAGON:["你可以公开自己手中的一张龙牌，让预言家借用它的普通能力；这张龙牌仍留在手中。也可以不借用。龙神的常驻能力不能被借用。","Choose a dragon in your hand to reveal and let the Prophet use its normal power. The dragon stays in your hand. You may decline. Dragon god abilities cannot be copied."],
  KEEP_SEER_CARD:["只有你能查看这 3 张牌。选 1 张加入自己的手牌，其余 2 张放入弃牌堆；保留牌的身份不向其他玩家公开。","Only you can inspect these 3 cards. Choose 1 for your hand and put the other 2 in the discard pile. Other players do not see the card you keep."],
  SEER_HAND_FULL_KEEP_TOP:["你的手牌已满 10 张。本牌桌的处理方式是：从这 3 张牌中选 1 张放回牌堆顶，其余 2 张弃掉，不再向手牌加牌。","Your hand already contains 10 cards. This table handles the limit by having you return 1 of these 3 cards to the top of the deck and discard the other 2; no card is added to your hand."],
  SORCERER_REPLACEMENT:["从公开的 3 张牌中选 1 张，替换自己牌阵中正在发动能力的牌。先完整结算新牌能力，再把其余 2 张放进公开下注区。","Choose 1 of the 3 revealed cards to replace the card using this power in your flight. Resolve the new card's power first, then put the other 2 cards in the public ante area."],
  STRENGTH_FLIGHT_ANTE:["从公开下注区选一张牌加入自己的手牌。同点数组合最多让你取 2 张，由你逐张选择；下注牌不足或手牌达到 10 张时停止。","Choose an ante card to add to your hand. A strength flight lets you take up to 2 cards, choosing one at a time. Stop if no antes remain or your hand reaches 10 cards."],
  TAKE_GOLD:["让每位对手把金币交给你","Have every opponent pay gold to you"],INCREASE_STAKES:["让每位对手把金币付入奖池","Have every opponent pay gold to the stakes"],
  PAY_FIVE:["向发动此能力的玩家支付 5 金币","Pay 5 gold to the player using this power"],KEEP_CARD:["保留这张牌，不替换或交换","Keep this card without replacing or exchanging it"],
  TRIGGER_POWER:["发动新牌的能力","Trigger the new card's power"],SKIP_POWER:["不发动新牌能力，仍保留这张牌","Keep the new card without triggering its power"],DO_NOT_COPY:["不公开手牌，也不借用能力","Keep your hand private and do not copy a power"],
  INVALID_CONFIG:["牌桌设置不完整或无效。","Invalid table setup."],INVALID_ACTION:["现在不能进行这个操作。","This action is unavailable."],
  UNKNOWN_SEAT:["请先加入牌桌。","Join the table first."],STALE_REVISION:["牌局已更新，请按最新桌面重试。","The table changed. Try again."],
  ACTION_ID_CONFLICT:["这次操作与先前的请求不一致。","This request conflicts with an earlier action."],
  NOT_YOUR_TURN:["正在等待其他玩家操作。","Waiting for another player."],CARD_NOT_AVAILABLE:["这张牌现在不可使用。","This card is unavailable."],
  INVALID_CHOICE:["请从当前提供的选项中选择。","Choose from the current options."],GAME_ENDED:["这局游戏已经结束。","This game has ended."],
  ADJUDICATION_REQUIRED:["规则未定义这个局面，需要整桌裁定。","This position needs a table ruling."],
  RULE_DECK_AND_DISCARD_EMPTY:["牌库和弃牌都已用尽，需要裁定。","Deck and discard are empty. A ruling is needed."],
  RULE_EMPTY_STAKES_TIE:["奖池已空但胜者并列，需要裁定。","Empty stakes with tied winners needs a ruling."],
  RULE_NO_ELIGIBLE_GAMBIT_WINNER:["所有玩家均受龙神禁胜条件影响，需要裁定。","Dragon gods exclude every winner. A ruling is needed."],
  RULE_TIED_WINNERS_ODD_HOLE_COIN:["胜者并列，请协商剩余金币的归属。","Tied winners must agree on the remaining coin."],
  RULE_EMPTY_HAND_AT_ANTE:["暗置时没有手牌，牌局需要检查。","No hand remains for ante. Check the game state."],
  RULE_UNBOUNDED_EFFECT_CHAIN:["连续能力未能结束，牌局已暂停。","A repeating power chain has paused the game."],
};
export function rulePrompt(code:string,language:"zh"|"en"):string {return RULE_PROMPTS[code]?.[language==="zh"?0:1]??code;}

/** Complete, independently phrased explanations, not shortened card-face labels.
 * "You" means the player resolving this power. The engine remains authoritative.
 * Silver Seer's full-hand handling is explicitly labelled as this table's ruling:
 * the publisher gives the ten-card limit but does not specify that return-to-top case. */
export const CARD_HINTS: Readonly<Record<string,readonly [string,string]>> = {
  "time-dragon":["这张牌发动能力时，从弃牌堆顶逐张拿取牌加入手牌，直到弃牌堆为空或手牌达到 10 张。拿不下的牌留在弃牌堆，不从牌库补牌。","When this power triggers, take cards from the top of the discard pile into your hand until it is empty or you hold 10 cards. Leave any remaining discards in place; do not draw from the deck."],
  black:["这张牌发动能力时，你从中央奖池取走 3 金币，加入自己的金币。奖池不足 3 金币就全部取走；奖池一旦被取空，本轮局立即结束并结算。","When this power triggers, move 3 gold from the central stakes to your own hoard. If fewer than 3 gold remain, take the amount available. Emptying the stakes immediately ends and scores this gambit."],
  blue:["这张牌发动能力时，由你选择一种方式，所有对手都按同一种方式付款：每位对手向你支付 1 金币；或者，你的牌阵每有 1 张牌，每位对手就向中央奖池支付 1 金币。数牌阵张数时，包括刚打出的这张牌和凡人牌。","When this power triggers, choose one payment method for all opponents: each opponent pays 1 gold to you, or each opponent pays the central stakes 1 gold for every card in your flight. Count the card you just played and any mortals when counting your flight's cards."],
  brass:["这张牌发动能力时，你逆时针方向的相邻对手作出选择：从其手牌中交给你 1 张点数高于发动能力的牌的善龙，或者向你支付 5 金币。交牌时先向所有人展示，再加入你的手牌；没有符合条件的龙牌就必须付款。你的手牌已满 10 张时，对手仍可选择交牌，但只展示并保留那张牌，你拿不到它。","When this power triggers, your counterclockwise neighboring opponent chooses either to give you 1 good dragon from their hand whose strength exceeds the card using this power, or to pay you 5 gold. Reveal a given dragon to everyone before adding it to your hand. If no eligible dragon is available, that opponent must pay. If you already hold 10 cards, the opponent may still choose a dragon, but reveals and keeps it instead of transferring it."],
  bronze:["这张牌发动能力时，你从公开下注区取点数最低的 2 张牌，加入自己的手牌。先选最低的一张，再选剩余牌中最低的一张；遇到并列由你选择。只剩 1 张下注牌就取 1 张。你已有 9 张手牌时，从选出的两张中只保留 1 张，另一张留在下注区；已有 10 张手牌时不取牌。","When this power triggers, add the 2 lowest-strength public ante cards to your hand. Choose a lowest card first, then a lowest card among those remaining; you decide between ties. If only 1 ante remains, take that card. With 9 cards already in hand, keep just 1 of the two selected cards and leave the other in the ante area. With 10 hand cards, take none."],
  copper:["这张牌发动能力时，先把它放入弃牌堆，再把牌堆顶的 1 张牌正面朝上放到它原来的牌阵位置。新牌无论点数多少，都发动自己的能力。此后按新牌的点数计算牌阵、下一位玩家的触发条件和下一轮领出者；先完整结算替换及能力，再检查组合奖励。若新牌还是赤铜龙，就继续同样的替换。","When this power triggers, discard this card, then place the top card of the deck face up in its former flight position. The new card triggers its own power at any strength. Use that replacement for your flight total, the next player's trigger comparison and the next round's leader. Finish replacements and powers before checking flight rewards. Another Copper Dragon repeats this replacement process."],
  gold:["这张牌发动能力时，数一数自己当前牌阵中的善龙，只数牌阵中的善龙，不数手牌；金龙若在牌阵中也计入。每有 1 张善龙，你就从牌堆里抽 1 张牌加入自己的手牌；手牌达到 10 张时停止抽牌。","When this power triggers, count the good dragons currently in your own flight, including Gold Dragon if it is in that flight. Do not count dragons in your hand. For each good dragon, draw 1 card from the deck into your hand. Stop drawing when your hand contains 10 cards."],
  green:["这张牌发动能力时，你顺时针方向的相邻对手作出选择：从其手牌中交给你 1 张点数低于发动能力的牌的邪龙，或者向你支付 5 金币。交牌时先向所有人展示，再加入你的手牌；没有符合条件的龙牌就必须付款。你的手牌已满 10 张时，对手仍可选择交牌，但只展示并保留那张牌，你拿不到它。","When this power triggers, your clockwise neighboring opponent chooses either to give you 1 evil dragon from their hand whose strength is below the card using this power, or to pay you 5 gold. Reveal a given dragon to everyone before adding it to your hand. If no eligible dragon is available, that opponent must pay. If you already hold 10 cards, the opponent may still choose a dragon, but reveals and keeps it instead of transferring it."],
  red:["这张牌发动能力时，只比较所有对手当前的牌阵总强度，不计你自己的牌阵。总强度最高的对手向你支付 1 金币；若最高值并列，由你选择其中一位。然后从该对手的手牌中随机拿走 1 张，加入你的手牌，其他玩家不看这张牌。对手没有手牌，或你已有 10 张手牌时，不转移卡牌；金币仍照常支付。","When this power triggers, compare opponents' current flight totals, excluding your own. An opponent with the highest total pays you 1 gold; if several tie, choose one of them. Then take 1 random card from that opponent's hand into yours without revealing it to the other players. No card transfers if that opponent has none or you already hold 10 cards; the gold payment still applies."],
  silver:["这张牌发动能力时，每位当前牌阵中至少有 1 张善龙的玩家，都从牌堆里抽 1 张牌加入自己的手牌。你也算在内，但只数牌阵中的善龙，不数手牌。从你开始，再按顺时针方向依次处理；手牌已满 10 张的玩家不再抽牌。","When this power triggers, every player whose current flight contains at least 1 good dragon draws 1 card from the deck into their hand. This includes you, but only good dragons in flights qualify. Do not count dragons in your hand. Resolve your draw first, then proceed clockwise. A player already holding 10 cards does not draw."],
  white:["这张牌发动能力时，只比较所有对手当前的牌阵总强度，不计你自己的牌阵。总强度最低的对手向你支付 2 金币；若最低值并列，由你选择其中一位付款。","When this power triggers, compare opponents' current flight totals, excluding your own. The opponent with the lowest total pays you 2 gold. If several opponents share that lowest total, choose one of them to pay."],
  bahamut:["龙神限制一直生效，无须触发：只要你的牌阵中同时有巴哈姆特和任意邪龙，你就不能赢得本轮局。另有一个需要正常触发的能力：每位在自己牌阵中同时有善龙和邪龙的对手，向你支付 10 金币。判断的是每位对手各自的牌阵，不是全桌合计。","The dragon god restriction applies without triggering: you cannot win this gambit while your flight contains both Bahamut and any evil dragon. Its separate normal power requires a trigger. When that power triggers, each opponent whose own flight contains both a good dragon and an evil dragon pays you 10 gold. Check each opponent's flight separately, not the table as a whole."],
  "black-raider":["这张牌发动能力时，你先从中央奖池取 1 金币加入自己的金币。若奖池因此取空，本轮局立即结束，后续收款不再执行。否则，从你顺时针方向的相邻对手开始，按顺时针依次收款：第一位付你 2 金币，第二位付你 3 金币，此后每位比前一位多付 1 金币，直到每位对手都处理一次。","When this power triggers, first move 1 gold from the central stakes to your hoard. If this empties the stakes, the gambit ends immediately and no later payments occur. Otherwise, collect gold clockwise starting with your clockwise neighboring opponent: that player pays you 2 gold, the next pays you 3 gold, and each subsequent opponent pays 1 more than the previous one. Process each opponent once."],
  "blue-overlord":["这张牌发动能力时，由你选择一种方式，所有对手都按同一种方式付款：每位对手向你支付 2 金币；或者，你的牌阵每有 1 张牌，每位对手就向中央奖池支付 2 金币。数牌阵张数时，包括正在发动能力的这张牌和凡人牌。","When this power triggers, choose one payment method for all opponents: each opponent pays 2 gold to you, or each opponent pays the central stakes 2 gold for every card in your flight. Include the card using this power and any mortals when counting your flight's cards."],
  "brass-sultan":["这张牌发动能力时，你顺时针和逆时针方向的相邻对手各自选择：从其手牌中交给你 1 张点数高于发动能力的牌的善龙，或者向你支付 5 金币。交出的牌要公开；没有符合条件的龙牌就必须付款。两人游戏中，同一个对手要分别处理顺时针和逆时针这两次要求。你已有 10 张手牌时，对手选中的龙牌只展示并留在其手中。","When this power triggers, your clockwise and counterclockwise neighboring opponents each choose either to give you 1 good dragon from their hand with strength above the card using this power, or to pay you 5 gold. A chosen dragon must be revealed; an opponent with no eligible dragon must pay. In a two-player game, the same opponent resolves this demand twice, once for each side. If you already hold 10 cards, a chosen dragon is revealed but stays in that opponent's hand."],
  "bronze-warlord":["这张牌发动能力时，你从公开下注区取点数最低的 2 张牌加入手牌，逐张从剩余最低点数的牌中选择，并列由你决定。只剩 1 张就取 1 张；已有 9 张手牌时，从选出的两张中保留 1 张，另一张留在下注区；已有 10 张时不取牌。另外，第三轮结束时如果你没有赢得本轮局，所有玩家再打第四轮。奖池提前取空仍会立即结束轮局。","When this power triggers, take the 2 lowest-strength public ante cards into your hand, choosing a lowest remaining card each time and deciding between ties. Take only 1 if that is all that remains. With 9 hand cards, keep 1 of the two selected cards and leave the other in the ante area; with 10, take none. In addition, if you do not win this gambit at the end of round three, everyone plays a fourth round. Empty stakes still end the gambit immediately."],
  "chromatic-wyrmling":["这张牌发动能力时，你可以把它弃掉，再从自己的手牌中选 1 张邪龙，正面朝上放到它原来的牌阵位置。新牌无论点数多少，都发动自己的能力。你也可以保留正在发动能力的原牌，不替换；手中没有邪龙时就保持原样。先完整结算新牌能力和组合奖励，再判断是否因手牌用尽而需要买牌。","When this power triggers, you may discard it and choose 1 evil dragon from your own hand to place face up in its former flight position. The replacement triggers its own power at any strength. You may instead keep the original card using this power; if you hold no evil dragon, nothing is replaced. Finish the new power and flight rewards before checking whether an empty hand requires a card purchase."],
  "copper-trickster":["这张牌发动能力时，你必须选自己牌阵中的另一张牌，先将它弃掉，再用牌堆顶的 1 张牌替换到原位置。随后你可以选择发动新牌能力，也可以不发动，新牌都会留在牌阵中。没有其他牌可替换时，此能力无效果。若你的大法师效果正在本轮局生效，新牌必须发动能力，不能跳过。","When this power triggers, you must choose another card in your own flight, discard it, and replace it in the same position with the top card of the deck. You then choose whether to trigger the new card's power; the card remains in your flight either way. If no other flight card exists, this power does nothing. If your Archmage effect is active this gambit, the new power must trigger and cannot be skipped."],
  dracolich:["这张牌的能力发动后，等到本轮局结算时，你的牌阵中每有 1 张邪龙，总强度就额外增加 2 点；仍在牌阵中的龙巫妖自身也算。它不立即改变任何卡牌的点数，也不改变普通出牌时的触发比较或同点数组合。","After this power triggers, its bonus applies when this gambit is scored: add 2 to your flight's total strength for each evil dragon in that flight, including the Dracolich if it is still there. It does not immediately change any card's strength, normal play-trigger comparisons or strength-flight matches."],
  "gold-monarch":["这张牌发动能力时，你的当前牌阵每有 1 张善龙，就从牌堆里抽 1 张牌加入手牌，只数牌阵中的善龙，不数手牌；金龙君王若在牌阵中也计入。手牌达到 10 张就停止。另外，如果你赢得本轮局，在取得奖池后必须从自己的金币中向每位对手各支付 3 金币。你没有赢时，不需要支付这笔金币。","When this power triggers, draw 1 card from the deck into your hand for each good dragon currently in your flight, including Gold Monarch if it is in that flight. Do not count dragons in your hand. Stop at 10 hand cards. In addition, if you win this gambit, you must pay each opponent 3 gold from your own hoard after receiving the stakes. You owe no such payment if you do not win."],
  "green-schemer":["这张牌发动能力时，你顺时针和逆时针方向的相邻对手各自选择：从其手牌中交给你 1 张点数高于发动能力的牌的邪龙，或者向你支付 5 金币。交出的牌要公开；没有符合条件的龙牌就必须付款。两人游戏中，同一个对手要分别处理顺时针和逆时针这两次要求。你已有 10 张手牌时，对手选中的龙牌只展示并留在其手中。","When this power triggers, your clockwise and counterclockwise neighboring opponents each choose either to give you 1 evil dragon from their hand with strength above the card using this power, or to pay you 5 gold. A chosen dragon must be revealed; an opponent with no eligible dragon must pay. In a two-player game, the same opponent resolves this demand twice, once for each side. If you already hold 10 cards, a chosen dragon is revealed but stays in that opponent's hand."],
  "metallic-wyrmling":["这张牌发动能力时，你可以把它弃掉，再从自己的手牌中选 1 张善龙，正面朝上放到它原来的牌阵位置。新牌无论点数多少，都发动自己的能力。你也可以保留正在发动能力的原牌，不替换；手中没有善龙时就保持原样。先完整结算新牌能力和组合奖励，再判断是否因手牌用尽而需要买牌。","When this power triggers, you may discard it and choose 1 good dragon from your own hand to place face up in its former flight position. The replacement triggers its own power at any strength. You may instead keep the original card using this power; if you hold no good dragon, nothing is replaced. Finish the new power and flight rewards before checking whether an empty hand requires a card purchase."],
  "red-destroyer":["这张牌发动能力时，只比较所有对手当前的牌阵总强度，不计你自己的牌阵。总强度最高的对手向你支付 10 金币；若最高值并列，由你选择其中一位。然后从该对手的手牌中随机拿走 1 张，加入你的手牌，其他玩家不看这张牌。对手没有手牌，或你已有 10 张手牌时，不转移卡牌；金币仍照常支付。","When this power triggers, compare opponents' current flight totals, excluding your own. An opponent with the highest total pays you 10 gold; if several tie, choose one of them. Then take 1 random card from that opponent's hand into yours without revealing it to the other players. No card transfers if that opponent has none or you already hold 10 cards; the gold payment still applies."],
  "silver-seer":["这张牌发动能力时，每位当前牌阵中至少有 1 张善龙的玩家，都从牌堆里抽 1 张牌加入手牌。从你开始，按顺时针方向依次处理；只数牌阵中的善龙，不数手牌，满 10 张手牌的人不抽。然后，只有你查看牌堆顶的 3 张牌，选 1 张加入手牌，其余 2 张弃掉，保留牌不公开。若这时你的手牌已满，本牌桌让你选 1 张放回牌堆顶、弃掉另 2 张，而不是再加手牌。","When this power triggers, every player with at least 1 good dragon in their current flight draws 1 card from the deck into their hand. Start with yourself and proceed clockwise; only good dragons in flights qualify, and players holding 10 cards do not draw. Do not count dragons in your hand. You then privately inspect the deck's top 3 cards, keep 1 in your hand without revealing it, and discard the other 2. If your hand is full at that point, this table has you return 1 card to the deck's top and discard the other 2 instead of adding a hand card."],
  tiamat:["这张牌没有需要触发的普通能力。它的龙神能力一直生效：组成同色牌阵时，提亚马特同时算黑、蓝、绿、红、白五种颜色，可以和其中任一颜色的两张龙牌组成同色组合。但只要你的牌阵中同时有提亚马特和任意善龙，你就不能赢得本轮局。","This card has no normal power to trigger. Its dragon god ability is always active: for color flights, Tiamat counts as black, blue, green, red and white at the same time, so it can complete a color flight with two dragons of any one of those colors. However, you cannot win this gambit while your flight contains both Tiamat and any good dragon."],
  "white-hunter":["这张牌发动能力时，比较每位对手当前的牌阵总强度与你自己的总强度。每位严格低于你的对手，都向你支付 3 金币；与你相同或高于你的对手不付款。计算你的总强度时包括正在发动能力的这张牌。","When this power triggers, compare every opponent's current flight total with your own. Each opponent whose total is strictly lower than yours pays you 3 gold. Equal or higher totals pay nothing. Include the card using this power in your own total."],
  archmage:["这张牌的能力发动后，直到本轮局结束，你之后打出的牌都能发动自己的能力，无须再满足点数不高于逆时针相邻玩家的条件。赤铜龙诡术师带来的新牌也必须发动能力。即使之后幻术师把大法师换走，已经给予你的这个效果也不会取消。","After this power triggers, every card you play later in this gambit triggers its own power without needing a strength at or below your counterclockwise neighbor's card. A replacement from Copper Trickster must also trigger. If an Illusionist later takes the Archmage from you, the effect already granted to you continues until this gambit ends."],
  dragonrider:["这张牌的能力发动后，等到本轮局结算时，它的点数改为你牌阵中点数最低的那张龙牌的点数。结算时没有龙牌，它就算 0 点；结算之前仍按印刷的 6 点处理。这次结算时的变点可以组成新的同点数牌阵；龙骑士仍是凡人，不因此变成龙牌。","After this power triggers, this card changes strength when the gambit is scored, matching the lowest-strength dragon in your flight. With no dragons at scoring, it is worth 0; before scoring, use its printed strength of 6. This change at scoring can complete a new strength flight. The Dragonrider remains a mortal, not a dragon."],
  dragonslayer:["这张牌发动能力时，你必须从任意玩家的牌阵中选择 1 张点数低于发动能力的牌的龙牌，将它放入弃牌堆；自己的龙牌也包括在内。屠龙者自身是 8 点，所以通常能弃掉 7 点或更低的龙牌。场上没有符合条件的龙牌时，无事发生；凡人牌不属于可弃掉的龙牌。","When this power triggers, choose 1 dragon from any player's flight whose strength is below the card using this power and put it in the discard pile. Your own dragons are eligible too, and the discard is mandatory if a valid target exists. The Dragonslayer itself has strength 8, so it normally removes a dragon of strength 7 or less. With no eligible dragon, nothing happens; mortals are not dragon targets."],
  druid:["这张牌的能力发动后，本轮局结算时改由牌阵总强度最低的玩家获胜，而不是最高者。第三轮结束后，如果最低总强度仍有多人并列，所有人继续多打一轮，直到某一轮结束时只有一位最低者。龙神的禁胜条件和奖池取空立即结束的规则仍然适用。","After this power triggers, the lowest flight total wins this gambit instead of the highest. If multiple players share the lowest total after round three, everyone plays another round, continuing until one player alone has the lowest total at a round's end. Dragon god restrictions and the immediate end for empty stakes still apply."],
  fool:["这张牌发动能力时，比较每位对手当前的牌阵总强度与你自己的总强度；你的总强度包括刚打出的愚者。每有 1 位对手严格高于你，你就从牌堆里抽 1 张牌加入手牌。与你并列的对手不提供抽牌；手牌达到 10 张时停止。","When this power triggers, compare each opponent's current flight total with yours, including the Fool you just played in your own total. For each opponent strictly above your total, draw 1 card from the deck into your hand. An opponent tied with you gives no draw. Stop when your hand contains 10 cards."],
  illusionist:["这张牌发动能力时，你可以选对手牌阵中的 1 张凡人牌，与自己的幻术师交换牌阵位置。换到你牌阵中的凡人牌无论点数多少，都发动自己的能力。你也可以不交换。交换得到商人王子时，之后本轮局的买牌款改由你收取；这不是从对手手牌中取牌。","When this power triggers, you may exchange your Illusionist with 1 mortal in an opponent's flight, placing each in the other's former position. The mortal now in your flight triggers its power at any strength. You may decline the exchange. If you receive the Merchant Prince, subsequent card-purchase payments this gambit go to you. This exchange never takes a card from an opponent's hand."],
  kobold:["这张牌发动能力时，你可以从自己剩余的手牌中选任意数量的牌，也可以一张都不选。先一次选好并确认，把所选牌全部放进弃牌堆；然后从牌堆里抽相同数量的牌，加入自己的手牌。不能先看抽到什么，再决定弃哪些牌。","When this power triggers, choose any number of your remaining hand cards, including none. Select and confirm all the cards to discard first, then put them in the discard pile. Draw the same number of cards from the deck into your hand. You cannot inspect replacement draws before deciding what to discard."],
  "merchant-prince":["这张牌的能力发动后，直到本轮局结束，玩家因手牌不足而必须买牌时，原本付给中央奖池的买牌金币改为交给你。它不改变买牌时机、定价或补至 4 张手牌的规则，也不改变其他付款。如果幻术师把商人王子换到另一位玩家的牌阵中，之后由那位玩家收取买牌款。","After this power triggers, required card purchases pay their gold to you rather than the central stakes for the rest of this gambit. This changes neither when cards must be bought, how their price is set, nor the rule to refill a purchased hand to 4 cards. Other payments are unaffected. If an Illusionist moves the Merchant Prince into another player's flight, that player receives subsequent purchase payments."],
  priest:["这张牌的能力发动后，本轮局的胜者不再独占中央奖池，而是与胜者顺时针方向的相邻玩家平分。奖池是奇数金币时，胜者多拿 1 金币。这里从胜者的座位沿顺时针确定收款人，不一定是你；其他判定谁获胜的规则不变。","After this power triggers, the winner of this gambit divides the central stakes equally with the winner's clockwise neighbor. If the stakes contain an odd number of gold, the winner receives the extra 1 gold. Find the recipient clockwise from the winner's seat, not from yours. The rules deciding who wins are unchanged."],
  princess:["这张牌发动能力时，你当前牌阵中的每张善龙都发动一次自己的能力，不论点数多少，也不论之前是否发动过。由你选择先后顺序，每次完整结算一张再处理下一张；轮到某张善龙时若它已离开你的牌阵，就跳过它。只处理公主发动时已有的那些善龙：赤铜龙替换出的新牌会按赤铜龙能力发动，但不会再被公主重复发动一次。","When this power triggers, each good dragon currently in your flight triggers its own power once, regardless of strength or whether it triggered earlier. Choose their order and finish each power before the next; skip a dragon if it has left your flight before its turn. This applies to the good dragons present when the Princess triggered: a new card replacing Copper Dragon triggers through Copper Dragon's power, but the Princess does not trigger that replacement an additional time."],
  prophet:["这张牌发动能力时，你可以向所有人展示自己手中的 1 张龙牌，让预言家借用那张龙的普通能力并执行；那张龙仍留在你的手牌里，不算打进牌阵。能力提到自身时按预言家处理，例如借用赤铜龙会替换预言家；涉及与自身比点数时按预言家的 10 点。你也可以不展示、不借用。龙神的常驻能力不能被借用。","When this power triggers, you may reveal 1 dragon from your hand to everyone and have the Prophet perform that dragon's normal power. The dragon stays in your hand and is not played into your flight. References to the card using the power apply to the Prophet: copying Copper Dragon replaces the Prophet, and strength comparisons against that card use the Prophet's 10. You may decline without revealing a card. Dragon god abilities cannot be copied."],
  queen:["这张牌发动能力时，检查每位对手自己的牌阵。只要其中同时有善龙和邪龙，该对手就向你支付 5 金币，然后你从其手牌中随机拿走 1 张加入手牌，其他玩家不看这张牌。从你顺时针方向的相邻对手开始，依次处理每位符合条件的对手。对手没有手牌或你已满 10 张手牌时，不转移卡牌，但金币照付。","When this power triggers, check each opponent's own flight. An opponent with both a good dragon and an evil dragon pays you 5 gold; you then take 1 random card from that opponent's hand into yours without showing it to other players. Process eligible opponents clockwise, starting with your clockwise neighbor. If an opponent has no hand cards or you already hold 10, no card transfers, but the gold payment still applies."],
  sorcerer:["这张牌发动能力时，先向所有人公开牌堆顶的 3 张牌。你选其中 1 张，把术士弃掉，并将所选牌放到它原来的牌阵位置；新牌无论点数多少，都发动自己的能力。等新牌及后续能力完整结算后，再把另外 2 张公开牌放进下注区，不能提前拿它们结算新牌能力。此后按替换牌计算本轮出牌点数；奖池中途取空会立即结束轮局。","When this power triggers, reveal the deck's top 3 cards to everyone. Choose 1, discard the Sorcerer and place the chosen card in its former flight position. The replacement triggers its own power at any strength. Only after that power and any resulting powers finish do the other 2 revealed cards enter the ante area; they are not available there to the replacement's power beforehand. Use the replacement as this turn's played card. Empty stakes interrupt this sequence and end the gambit immediately."],
  thief:["这张牌发动能力时，你从中央奖池取走 7 金币，加入自己的金币。奖池不足 7 金币就全部取走；奖池一旦被取空，本轮局立即结束并结算，不再继续等其他玩家出牌。","When this power triggers, move 7 gold from the central stakes to your own hoard. If fewer than 7 remain, take the amount available. Emptying the stakes immediately ends and scores this gambit without waiting for more players to play."],
  wyrmpriest:["这张牌的能力发动后，直到本轮局结束，组成同色牌阵时它可以算任意一种龙的颜色，无须预先指定一种颜色，也可以在不同同色组合中分别使用。它仍然是一张凡人牌，也能参与三张凡人的组合；不会因为配色而变成善龙或邪龙，点数也不改变。","After this power triggers, this card can match any dragon color for color flights until this gambit ends. You do not lock it to one color, and it can contribute to different color flights. It remains a mortal and can still form a three-mortal flight; matching a color does not make it a good or evil dragon or change its strength."],
};
export function cardHint(family:string,language:"zh"|"en"):string{return language==="zh"?CUSTOM_PACK[family]?.[1]??PRINTED_PACK[family]?.[1]??family:CARD_HINTS[family]?.[1]??family;}
export function cardExplanation(family:string,language:"zh"|"en"):string{return CARD_HINTS[family]?.[language==="zh"?0:1]??family;}
const CARD_NAMES_ZH:Readonly<Record<string,string>>={
  black:"黑龙",blue:"蓝龙",brass:"黄铜龙",bronze:"青铜龙",copper:"赤铜龙",gold:"金龙",green:"绿龙",red:"红龙",silver:"银龙",white:"白龙",
  bahamut:"巴哈姆特","black-raider":"黑龙掠夺者","blue-overlord":"蓝龙霸主","brass-sultan":"黄铜龙苏丹","bronze-warlord":"青铜龙战将",
  "chromatic-wyrmling":"彩色雏龙","copper-trickster":"赤铜龙诡术师",dracolich:"龙巫妖","gold-monarch":"金龙君王","green-schemer":"绿龙谋士",
  "metallic-wyrmling":"金属雏龙","red-destroyer":"红龙毁灭者","silver-seer":"银龙先知",tiamat:"提亚马特","white-hunter":"白龙猎手",
  archmage:"大法师",dragonrider:"龙骑士",dragonslayer:"屠龙者",druid:"德鲁伊",fool:"愚者",illusionist:"幻术师",kobold:"狗头人",
  "merchant-prince":"商人王子",priest:"祭司",princess:"公主",prophet:"预言家",queen:"女王",sorcerer:"术士",thief:"盗贼",wyrmpriest:"龙祭司",
};
export function cardName(id:string,language:"zh"|"en"):string {const value=card(id);return language==="zh"?CUSTOM_PACK[value.family]?.[0]??PRINTED_PACK[value.family]?.[0]??CARD_NAMES_ZH[value.family]??value.name:value.name;}
