import {rulePrompt, RULE_PROMPTS} from "./rules/prompts";
export type TableLanguage="zh"|"en";
const TEXT:Record<string,readonly [string,string]>={
 title:["三龙牌","Three-Dragon Ante"],edition:["传奇版 · 基础盒","Legendary Edition · Base box"],close:["关闭窗口","Close window"],
 backToMap:["返回地图","Back to map"],minimize:["缩小牌桌","Minimize table"],expand:["展开牌桌","Expand table"],inspectCard:["查看卡牌","Inspect card"],closePreview:["关闭卡牌预览","Close card preview"],inspectHint:["悬停或点 i 查看能力","Hover or tap i to read powers"],
 create:["创建牌桌","Create table"],join:["加入牌桌","Join table"],leave:["离开座位","Leave seat"],start:["开始游戏","Start game"],
 newGame:["准备新局","Prepare new game"],retry:["重新连接","Reconnect"],waiting:["等待其他玩家","Waiting for other players"],
 lobby:["2–6 人即可开始，每局随机使用 10 张特殊牌。","Start with 2–6 players. Each game uses 10 random special cards."],
 noTable:["邀请同房间的伙伴一起玩三龙牌。","Play Three-Dragon Ante with others in this room."],
 host:["主持人","Host"],you:["你","You"],spectator:["正在旁观；本局手牌仅座位本人可见。","Spectating. Hands are visible only to their owners."],
 watch:["游戏进行中，可旁观；下一局开始前可加入。","Game in progress. Watch now and join before the next game."],
 seated:["已入座，等待主持人开始。","Seated. Waiting for the host to start."],needPlayers:["等待至少两位玩家入座。","Waiting for at least two players."],
 closeHint:["关窗后仍保留座位，可随时重新打开。","Closing keeps your seat. Reopen at any time."],
 gold:["金币","Gold"],debt:["欠款","Debt"],handCount:["手牌","Hand"],strength:["当前点数","Current strength"],
 stakes:["奖池","Stakes"],hole:["偿债池","Hole"],deck:["牌库","Deck"],gambit:["轮局","Gambit"],round:["轮","Round"],
 ante:["明牌区","Ante cards"],revealed:["公开待结算","Revealed, resolving"],flight:["已出牌","Flight"],hand:["你的手牌","Your hand"],
 antePrompt:["选一张手牌暗置下注；所有人选好后一起公开。","Choose a secret ante. Reveal together when everyone is ready."],
 playPrompt:["轮到你出牌。","Your turn to play."],confirmAnte:["暗置下注","Commit ante"],confirmPlay:["出这张牌","Play card"],confirmChoice:["确认选择","Confirm choice"],
 selection:["已选","Selected"],chooseRange:["可选数量","Allowed selection"],waitingFor:["等待","Waiting for"],
 committed:["已暗置下注","Ante committed"],ownAnte:["你的暗置下注","Your secret ante"],none:["暂无","None"],
 good:["善龙","Good dragon"],evil:["邪龙","Evil dragon"],mortal:["凡人","Mortal"],wild:["颜色百搭","Color wildcard"],rider:["结算时改点数","Strength changes at scoring"],
 leader:["领出","Leader"],acting:["正在操作","Acting"],abilityBy:["能力归属","Ability owner"],effects:["持续效果","Active effects"],
 discard:["弃牌堆","Discard pile"],history:["最近记录","Recent moves"],rules:["官方规则","Official rules"],help:["玩法速览","How to play"],
 helpText:["秘密下注决定奖池与领出者。依次出牌，通常打三轮；较弱或相同点数的牌会发动能力。先结算能力，再结算同色或同点数组合。金币不足会记欠款，在轮局结束时偿还；有人耗尽金币则结算整局。规则少数未定义的局面会暂停并说明原因。","Secret antes set the stakes and leader. Play in turn, normally for three rounds; equal or weaker cards trigger powers. Powers resolve before color and strength flight bonuses. Unpaid gold becomes debt, settled after the gambit. The game ends when someone has no gold. Undefined positions pause with an explanation."],
 paused:["需要整桌裁定 · 牌局已暂停","Table ruling needed · Game paused"],pausedHelp:["当前状态已保留。此版本不自动采用桌规；主持人可在大家确认后重新开局。","The current state is retained. This version does not apply house rules automatically; the host may start a new game after everyone agrees."],
 ended:["本局结束","Game ended"],winners:["胜者","Winners"],lastGambit:["上一轮局胜者","Previous gambit winner"],
 resetTitle:["结束当前牌局并回到准备大厅？","End this game and return to the lobby?"],resetBody:["本局手牌与金币进度会清空，座位会保留。请先与同桌玩家确认。回到大厅后可以加入或离席，由主持人重新开始发牌。","Hands and gold from this game will be cleared; seats are kept. Check with the table first. Players can join or leave in the lobby before the host starts dealing again."],
 cancel:["取消","Cancel"],confirmReset:["确认回到大厅","Return to lobby"],sending:["正在处理…","Processing…"],
 connecting:["正在连接牌桌…","Connecting to the table…"],hostOffline:["主持人已离线，等待其回来后继续。","The host is offline. Play resumes when they return."],
 privateSync:["正在同步你的私有手牌。","Syncing your private hand."],storageFailed:["本机无法保存恢复记录，请检查浏览器存储后重试。","Recovery storage is unavailable. Check browser storage and retry."],
 roomFull:["房间暂时无法保存牌桌设置，请重试。","The room cannot save the table right now. Retry."],tableExists:["房间已有牌桌，可直接加入。","A table already exists. Join it."],tableFull:["六个座位都已坐满，可以旁观。","All six seats are taken. You can watch."],
 notHost:["只有创建这张牌桌的玩家可以主持。","Only this table's creator can host."],cannotLeave:["游戏进行中无法离开座位；可以直接关窗。","You cannot leave a running game. You can close the window."],
 tooFewPlayers:["至少需要两名玩家。","At least two players are needed."],notSeated:["请先加入牌桌。","Join the table first."],staleTable:["牌桌已变化，请重新连接。","The table changed. Reconnect."],
 invalidCommand:["当前无法执行这个操作。","That action is unavailable."],requestFailed:["未收到处理结果，请重新连接后重试。","No result arrived. Reconnect and retry."],
 legacyArchiveRequired:["检测到旧版牌局的主持已离线。完整手牌与牌库保存在原主持浏览器中，无法从房间信息安全重建。请原主持回到原浏览器恢复牌局；现有牌局未被修改。","The legacy table host is offline. Full hands and deck are stored in the original host's browser and cannot be safely rebuilt from room metadata. Ask that host to restore the table in the original browser. The saved table has not been changed."],
 recoveryMissing:["主持端缺少本局恢复记录，无法还原手牌。请由原主持人恢复，或确认后重新开局。","The host lacks this game's recovery record. Restore the original host's session, or agree to start a new game."],
 protocolMismatch:["玩家与主持人的插件版本不同，请更新后重新连接。","Player and host versions differ. Update and reconnect."],
 druid:["最弱牌组获胜","Weakest flight wins"],priest:["胜者与左邻分奖池","Winner shares stakes with left neighbor"],merchant:["买牌款改付能力拥有者","Purchases pay the ability owner"],warlord:["第三轮未赢则加打一轮","Extra round if owner loses round three"],monarch:["获胜后每位对手获赠 3","On winning, give 3 to each opponent"],dracolich:["结算时每条邪龙 +2","At scoring, +2 per evil dragon"],archmage:["后续出牌均发动","Later cards trigger"],
 DECK_RESHUFFLED:["弃牌已重洗为牌库","Discard reshuffled into deck"],TOOK_STAKES:["领取奖池金币","Took gold from stakes"],PAID_STAKES:["支付到奖池","Paid into stakes"],PAID_PLAYER:["支付给玩家","Paid a player"],
 CARD_REVEALED:["展示手牌","Revealed a card"],CARDS_REVEALED:["公开牌","Revealed cards"],CARD_TRANSFERRED:["转交手牌","Transferred a card"],FLIGHT_REPLACED:["替换出场牌","Replaced a flight card"],BUY_PRICE:["强制买牌价格","Forced purchase price"],ANTE_REVEALED:["共同公开下注","Antes revealed together"],ANTE_ALL_TIED:["下注全部同点数，重新选牌","All antes tied; ante again"],GAMBIT_WON:["赢得轮局","Won the gambit"],GAME_ENDED:["整局结束","Game ended"],POWER_TRIGGERED:["发动能力","Power triggered"],SPECIAL_FLIGHT:["获得组合奖励","Special flight bonus"],DRAGON_REMOVED:["移除龙牌","Removed a dragon"],MORTALS_SWAPPED:["交换凡人牌","Swapped mortals"],CARD_PLAYED:["出牌","Played a card"],
};
export function tableText(code:string,lang:TableLanguage):string{return TEXT[code]?.[lang==="zh"?0:1]??(RULE_PROMPTS[code]?rulePrompt(code,lang):TEXT.requestFailed[lang==="zh"?0:1]);}
