import {card} from "./cards";
/** Independently written, concise interface prompts; never printed card text. */
export const RULE_PROMPTS: Readonly<Record<string,readonly [string,string]>> = {
  BLUE_DESTINATION:["金币放在哪里？","Choose gold destination"],
  GIVE_DRAGON_OR_GOLD:["交出符合条件的龙牌，或支付金币","Choose a dragon or payment"],
  LOWEST_ANTE_CARD:["选择一张最低点数的明牌","Choose a lowest ante card"],
  KEEP_ONE_ANTE_CARD:["手牌将满，选择保留的一张","Choose one to keep"],
  REPLACE_OTHER_FLIGHT_CARD:["选择替换哪张已出牌","Choose a flight card to replace"],
  REPLACE_WYRMLING:["替换雏龙，或保留它","Replace or keep the wyrmling"],
  TRIGGER_REPLACEMENT:["是否发动替换牌的能力？","Trigger the replacement?"],
  WEAKEST_OPPONENT:["选择最弱的对手","Choose a weakest opponent"],
  STRONGEST_OPPONENT:["选择最强的对手","Choose a strongest opponent"],
  REMOVE_WEAKER_DRAGON:["选择移除哪张弱龙牌","Choose a weaker dragon to remove"],
  EXCHANGE_HAND_CARDS:["选择要换掉的手牌，可不选","Choose cards to exchange"],
  SWAP_MORTAL:["交换凡人牌，或保持原样","Swap or keep your mortal"],
  NEXT_GOOD_DRAGON_POWER:["选择接下来发动的善龙","Choose the next good dragon"],
  COPY_HAND_DRAGON:["展示并借用一张龙牌的能力","Choose a dragon to copy"],
  KEEP_SEER_CARD:["这几张只有你可见，选择保留牌","Privately choose one card"],
  SEER_HAND_FULL_KEEP_TOP:["手牌已满，选择留在牌库顶的一张","Hand full: choose the deck's top card"],
  SORCERER_REPLACEMENT:["选择新的出场牌","Choose your replacement"],
  STRENGTH_FLIGHT_ANTE:["选择加入手牌的明牌","Choose an ante card"],
  TAKE_GOLD:["收进自己的金币堆","Take gold"],INCREASE_STAKES:["加入奖池","Add to stakes"],
  PAY_FIVE:["支付 5 金币","Pay 5 gold"],KEEP_CARD:["保留当前牌","Keep this card"],
  TRIGGER_POWER:["发动能力","Trigger power"],SKIP_POWER:["不发动","Skip power"],DO_NOT_COPY:["不借用能力","Do not copy"],
  INVALID_CONFIG:["牌桌设置不完整或无效。","Invalid table setup."],INVALID_ACTION:["现在不能进行这个操作。","This action is unavailable."],
  UNKNOWN_SEAT:["请先加入牌桌。","Join the table first."],STALE_REVISION:["牌局已更新，请按最新桌面重试。","The table changed. Try again."],
  ACTION_ID_CONFLICT:["这次操作与先前的请求不一致。","This request conflicts with an earlier action."],
  NOT_YOUR_TURN:["正在等待其他玩家操作。","Waiting for another player."],CARD_NOT_AVAILABLE:["这张牌现在不可使用。","This card is unavailable."],
  INVALID_CHOICE:["请从当前提供的选项中选择。","Choose from the current options."],GAME_ENDED:["这局游戏已经结束。","This game has ended."],
  ADJUDICATION_REQUIRED:["规则未定义这个局面，需要整桌裁定。","This position needs a table ruling."],
  RULE_DECK_AND_DISCARD_EMPTY:["牌库和弃牌都已用尽，需要裁定。","Deck and discard are empty. A ruling is needed."],
  RULE_EMPTY_STAKES_TIE:["奖池已空但胜者并列，需要裁定。","Empty stakes with tied winners needs a ruling."],
  RULE_NO_ELIGIBLE_GAMBIT_WINNER:["所有玩家均受龙神禁胜条件影响，需要裁定。","Dragon gods exclude every winner. A ruling is needed."],
  RULE_TIED_WINNERS_ODD_HOLE_COIN:["胜者并列，请协商剩余金币的归属。","Tied winners must agree on the remaining coin."],
  RULE_EMPTY_HAND_AT_ANTE:["下注时没有手牌，牌局需要检查。","No hand remains for ante. Check the game state."],
  RULE_UNBOUNDED_EFFECT_CHAIN:["连续能力未能结束，牌局已暂停。","A repeating power chain has paused the game."],
};
export function rulePrompt(code:string,language:"zh"|"en"):string {return RULE_PROMPTS[code]?.[language==="zh"?0:1]??code;}

/** Short decision aids; deliberately not a reproduction of printed powers.
 * Full resolution stays in the engine, including hand limits and interrupts. */
export const CARD_HINTS: Readonly<Record<string,readonly [string,string]>> = {
  black:["从奖池取 3 金币。","Take 3 from stakes."],blue:["收每人 1 金币，或按你的牌数增加奖池。","Collect 1 each, or grow stakes by flight size."],
  brass:["右邻选择交出更强善龙或付 5。","Right neighbor offers a stronger good dragon or 5 gold."],bronze:["取两张最弱明牌；平局可选。","Take two weakest ante cards."],
  copper:["随机替换自身，继续发动新牌。","Replace itself from deck; trigger the replacement."],gold:["按自己善龙数量抓牌。","Draw for your good dragons."],
  green:["左邻选择交出更弱邪龙或付 5。","Left neighbor offers a weaker evil dragon or 5 gold."],red:["最强对手付 1，并随机交出手牌。","Strongest opponent pays 1 and loses a random card."],
  silver:["有善龙的玩家各抓一张。","Players with good dragons draw."],white:["最弱对手付 2。","Weakest opponent pays 2."],
  bahamut:["混合阵营对手付 10；自身混入邪龙不能赢。","Mixed opponents pay 10; your evil dragons prevent victory."],
  "black-raider":["先取奖池 1，再沿左侧依次收 2、3……","Take 1 from stakes, then 2, 3… from clockwise opponents."],
  "blue-overlord":["蓝龙收款与加注翻倍。","Blue Dragon's payments are doubled."],"brass-sultan":["左右两邻分别执行黄铜龙的选择。","Both neighbors face the Brass Dragon choice."],
  "bronze-warlord":["取最弱明牌；第三轮没赢则再打一轮。","Take weakest antes; extend round three if you lose."],
  "chromatic-wyrmling":["可换成手中的邪龙，并发动它。","Optionally replace with a held evil dragon and trigger it."],
  "copper-trickster":["随机替换另一张出牌，再决定是否发动新牌。","Replace another flight card; optionally trigger it."],
  dracolich:["结算时每条己方邪龙使总分加 2。","At scoring, each evil dragon adds 2 to your total."],
  "gold-monarch":["按善龙抓牌；若赢，每位对手获赠 3。","Draw for good dragons; winning costs gifts of 3 each."],
  "green-schemer":["左右两邻分别执行绿龙的选择。","Both neighbors face the Green Dragon choice."],
  "metallic-wyrmling":["可换成手中的善龙，并发动它。","Optionally replace with a held good dragon and trigger it."],
  "red-destroyer":["最强对手付 10，并随机交出手牌。","Strongest opponent pays 10 and loses a random card."],
  "silver-seer":["银龙抓牌后，私看三张并挑选。","Silver draw, then a private three-card selection."],
  tiamat:["自带五种邪龙颜色；混入善龙不能赢。","Always matches five evil colors; your good dragons prevent victory."],
  "white-hunter":["每个比你弱的对手付 3。","Every weaker opponent pays 3."],
  archmage:["本轮局后续出牌都会发动。","Your later cards trigger this gambit."],
  dragonrider:["结算时变为己方最弱龙的点数。","At scoring, match your weakest dragon."],
  dragonslayer:["必须移除场上一条更弱的龙，可包括己方。","Remove a weaker dragon, including your own if necessary."],
  druid:["本轮局改由最弱牌组获胜。","Weakest flight wins this gambit."],fool:["每个比你强的对手让你抓一张。","Draw for stronger opponents."],
  illusionist:["可交换对手凡人牌并发动得到的牌。","Optionally swap for an opposing mortal and trigger it."],
  kobold:["自选手牌换掉，可一张也不换。","Exchange any chosen hand cards."],"merchant-prince":["本轮局买牌款转交给你。","Card purchases pay you this gambit."],
  priest:["胜者与其左邻分享奖池。","Winner shares stakes with their left neighbor."],princess:["按你选择的顺序发动己方善龙。","Trigger your good dragons in your chosen order."],
  prophet:["可展示手中龙牌，借用它的普通能力。","Optionally copy a held dragon's normal power."],queen:["混合阵营对手各付 5，并随机交出手牌。","Mixed opponents pay 5 and lose a random card."],
  sorcerer:["公开三张选一替换自己，其余入明牌区。","Replace with one of three revealed cards; others become antes."],
  thief:["从奖池取 7 金币。","Take 7 from stakes."],wyrmpriest:["本轮局可参与任意颜色组合，仍是凡人。","Wildcard for color flights; still a mortal."],
};
export function cardHint(family:string,language:"zh"|"en"):string{return CARD_HINTS[family]?.[language==="zh"?0:1]??family;}
const CARD_NAMES_ZH:Readonly<Record<string,string>>={
  black:"黑龙",blue:"蓝龙",brass:"黄铜龙",bronze:"青铜龙",copper:"赤铜龙",gold:"金龙",green:"绿龙",red:"红龙",silver:"银龙",white:"白龙",
  bahamut:"巴哈姆特","black-raider":"黑龙掠夺者","blue-overlord":"蓝龙霸主","brass-sultan":"黄铜龙苏丹","bronze-warlord":"青铜龙战将",
  "chromatic-wyrmling":"彩色雏龙","copper-trickster":"赤铜龙诡术师",dracolich:"龙巫妖","gold-monarch":"金龙君王","green-schemer":"绿龙谋士",
  "metallic-wyrmling":"金属雏龙","red-destroyer":"红龙毁灭者","silver-seer":"银龙先知",tiamat:"提亚马特","white-hunter":"白龙猎手",
  archmage:"大法师",dragonrider:"龙骑士",dragonslayer:"屠龙者",druid:"德鲁伊",fool:"愚者",illusionist:"幻术师",kobold:"狗头人",
  "merchant-prince":"商人王子",priest:"祭司",princess:"公主",prophet:"预言家",queen:"女王",sorcerer:"术士",thief:"盗贼",wyrmpriest:"龙祭司",
};
export function cardName(id:string,language:"zh"|"en"):string {const value=card(id);return language==="zh"?CARD_NAMES_ZH[value.family]??value.name:value.name;}
